
kafka:
  bootstrapServers: localhost
  securityProtocol: sec
  saslMechanism: sasl
  saslJaasConfig: saslConfig


id-verification:
  email:
    senderName : 'Britenet'
  kafka:
    enabled: false
    topic: topic
    group-id: "kafka-consumer-group-id"


external-system:
  file-service2:
    address: 'http://localhost:9000/file-service/'



spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:hermetization
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [trackId:%X{trackId}] %msg%n"